velican2/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path("start/", views.Start.as_view(), name="start"),
    path("sites/", views.Sites.as_view(), name="sites"),
    path("sites/<str:site>/", views.Site.as_view(), name="site"),
    path("sites/<str:site>/update.html", views.SiteEdit.as_view(), name="site-edit"),
    path("sites/<str:site>/publish.html", views.Publish.as_view(), name="publish"),
    path("sites/<str:site>/images.html", views.Images.as_view(), name="images"),
    path("sites/<str:site>/category/create.html", views.CategoryCreate.as_view(), name="category-add"),
    path("sites/<str:site>/post/create.html", views.PostCreate.as_view(), name="post-add"),
    path("sites/<str:site>/post/<int:post>/update.html", views.Post.as_view(), name="post"),
    path("sites/<str:site>/post/<int:post>/delete.html", views.PostDelete.as_view(), name="post-delete"),
    path("legal.html", views.render_static_page),
]

velican2/engines/pelican/urls.py
from django.urls import path
from . import views

app_name="pelican"
urlpatterns = [
    path("", views.SettingsList.as_view(), name="settings"),
    path("<str:site>/", views.SettingsDetail.as_view(), name="setting"),
    path("<str:site>/themes/", views.ThemeList.as_view(), name="themes"),
    path("<str:site>/import-article/", views.ImportArticle.as_view(), name="import-article"),
]

velican2/exporters/git/urls.py
from django.urls import path
from . import views

app_name = "git"

urlpatterns = [
    path('<str:site>/connect', views.Create.as_view(), name="connect"),
]

velican2/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve as serve_static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pelican/', include('velican2.engines.pelican.urls')),
    path('git/', include('velican2.exporters.git.urls')),
    path('', include('velican2.core.urls', namespace="core")),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG :
    urlpatterns.insert(0,
        re_path(r'^media/(?P<path>.*)$', serve_static, {'document_root': settings.MEDIA_ROOT}),
    )

velican2/core/forms.py
from typing import Any, Dict
from datetime import date
from django import forms

from django.core.exceptions import ValidationError
from django.db.transaction import atomic
from django.conf import settings
from django.contrib.auth import models as auth

from martor.fields import MartorFormField

from . import logger
from .models import Category, Site, Post, Publish
from ..engines.pelican import models as pelican


class StartForm(forms.Form):
    title = forms.CharField(max_length=128)
    subtitle = forms.CharField(max_length=256, required=False)
    own_domain = forms.CharField(max_length=100, required=False)
    subdomain = forms.CharField(max_length=100, required=False)
    pelican_theme = forms.ChoiceField(choices=lambda: pelican.Theme.objects.all().values_list('name', 'name'), required=True)  # TODO: change to not-required once more engines are ready

    def clean(self) -> Dict[str, Any]:
        cleaned_data = super().clean()
        own_domain = cleaned_data.get("own_domain")
        subdomain = cleaned_data.get("subdomain")

        if not (own_domain or subdomain):
            self.add_error('own_domain', ValidationError("Specify either your own domain or a subdomain"))
            self.add_error('subdomain', ValidationError("Specify either your own domain or a subdomain"))

    @atomic
    def save(self, admin: auth.User):
        """Should return an object (class) that will be used in redirect URL contruction"""
        data = self.cleaned_data
        logger.info(data)
        site_kwargs = {"admin": admin}
        if data.get('pelican_theme'):
            site_kwargs['engine'] = "pelican"
        if data.get('own_domain'):
            site_kwargs['urn'] = data.get("own_domain")
        else:
            site_kwargs['urn'] = data.get("subdomain") + "." + settings.DOMAIN
        site_kwargs['title'] = data.get('title')
        site_kwargs['subtitle'] = data.get('subtitle')
        # create site and the engine's settings will auto-create with it
        site = Site.objects.create(**site_kwargs)

        if data.get('pelican_theme'):
            pelican, _ = pelican.Settings.objects.get_or_create(site=site)
            pelican.theme = pelican.Theme.objects.get(name=data.get('pelican_theme'))
            pelican.save()
        return site


class SiteEditForm(forms.ModelForm):
    class Meta:
        model = Site
        exclude = ("urn", "admin", "staff")


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "lang", "description", "category", "translation_of")


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ("name", )


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "lang", "draft", "description", "punchline", "content", "broadcast", "updated")
    action = forms.CharField(initial="save")
    content = MartorFormField()

    def clean(self):
        self.cleaned_data['updated'] = date.today()
        if self.cleaned_data['action'] == "publish":
            self.cleaned_data['draft'] = False
            self.publish = Publish(site=self.initial['site'])
            self.publish.clean()
        return super().clean()
    
    def save(self, commit=True):
        instance = super().save(commit)
        if hasattr(self, 'publish'):
            instance.publish(commit=True)
            self.publish.post = instance
            self.publish.save()
        return instance

velican2/core/views.py
import json

from io import BytesIO
from datetime import date
from typing import Any, Dict
from django import http
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.urls import reverse
from django.views import generic as generic_views
from django.views.generic import edit as edit_views
from django.utils.translation import gettext as _
from pathlib import Path

from markdownx import utils as image_utils
from martor.utils import LazyEncoder
from velican2.engines import pelican

from . import models
from . import forms
from . import logger


def index(request: http.HttpRequest):
    return render(request, "index.html")


class Start(LoginRequiredMixin, generic_views.FormView):
    form_class = forms.StartForm
    template_name = "start.html"

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(admin=self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("core:post-add", site=self.object.urn)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        return super().get_context_data(
            urn=settings.DOMAIN,
            pelican_themes=pelican.models.Theme.objects.exclude(image__isnull=True).exclude(image=""),
            **kwargs)


class SiteMixin:
    def dispatch(self, request, site:str, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect("account_login")
        try:
            self.site = models.Site.objects.filter(admin=request.user, urn=site).get()
        except models.Site.DoesNotExist:
            messages.info(request, _("Site required"))
            return redirect("core:start")
        return super().dispatch(request, *args, site=site, **kwargs)
    
    def get_context_data(self, *args, **kwargs):
        return super().get_context_data(*args, **kwargs, site=self.site)


class PostMixin:
    def dispatch(self, request, post:int, *args, **kwargs):
        try:
            self._post = models.Post.objects.get(pk=post)
            if self._post.site != self.site:
               logger.error(f"User {request.user} trying to access else's post {post}")
               raise models.Site.DoesNotExist()
        except models.Site.DoesNotExist:
            messages.info(request, _("Post does not exists"))
            return redirect("core:start")
        return super().dispatch(request, *args, post=post, **kwargs)

    def get_context_data(self, *args, **kwargs):
        return super().get_context_data(*args, **kwargs, post=self._post)


class Site(SiteMixin, generic_views.DetailView):
    template_name = "site.html"

    def get_object(self):
        return self.site

    def get_context_data(self, *args, **kwargs):
        from velican2.exporters.git import models as git 
        return super().get_context_data(
            *args,
            posts=models.Post.objects.filter(site=self.site, translation_of__isnull=True, draft=False)[:5],
            drafts=models.Post.objects.filter(site=self.site, translation_of__isnull=True, draft=True)[:15],
            last_deploy=models.Publish.objects.filter(site=self.site).order_by("-started").first(),
            git_exporter=git.Settings.objects.filter(site=self.site).first(),
            **kwargs)


class SiteEdit(SiteMixin, generic_views.UpdateView):
    template_name = "site-edit.html"
    form_class = forms.SiteEditForm

    def get_object(self):
        return self.site
    
    def get_success_url(self) -> str:
        return reverse("core:site", kwargs={"site": self.site.urn})


class Sites(LoginRequiredMixin, generic_views.ListView):
    template_name = "sites.html"

    def get_queryset(self):
        return models.Site.objects.filter(admin=self.request.user)

    def get(self, request):
        sites_count = models.Site.objects.filter(admin=request.user).count()
        if sites_count == 0:
            return redirect('core:start')
        if sites_count == 1:
            return redirect('core:site', models.Site.objects.get(admin=request.user).urn)
        return super().get(request)


def append_to_name(path: Path, appendix: str, sep="-") -> Path:
    return path.with_stem(path.stem + sep + appendix)


class PostCreate(SiteMixin, edit_views.CreateView):
    form_class = forms.PostCreateForm
    template_name = "post-add.html"

    # def get_context_data(self, *args, **kwargs):

    def get_context_data(self, *args, **kwargs):
        if self.request.GET.get("translation_of"):
            kwargs.update(post=models.Post.objects.filter(site=self.site, pk=int(self.request.GET.get("translation_of"))).first())
        return super().get_context_data(*args, **kwargs)

    def get_initial(self):
        return {'lang': self.site.lang, 'site': self.site, 'author': self.request.user}

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.site = self.site
        self.object.author = self.request.user
        if self.request.GET.get("translation_of"):
            self.translation_of = models.Post.objects.filter(site=self.site, pk=int(self.request.GET["translation_of"])).first()
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("core:post", kwargs=dict(site=self.site.urn, post=self.object.id))


class CategoryCreate(SiteMixin, edit_views.CreateView):
    form_class = forms.CategoryCreateForm
    template_name = "category-add.html"

    # def get_context_data(self, *args, **kwargs):

    def get_initial(self):
        return {'site': self.site}

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.site = self.site
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("core:post-add", kwargs=dict(site=self.site.urn))


class PostDelete(SiteMixin, PostMixin, edit_views.DeleteView):
    template_name = "post-delete.html"

    def get_object(self):
        return self._post

    def get_success_url(self):
        return reverse("core:site", kwargs=dict(site=self.site.urn))


class Post(SiteMixin, PostMixin, edit_views.UpdateView):
    form_class = forms.PostForm
    template_name = "post.html"
    image_upload_field = 'markdown-image-upload'
    image_types = [
        'image/png', 'image/jpg',
        'image/jpeg', 'image/pjpeg', 'image/gif'
    ]
    image_format = {
        'image/png': "png",
        'image/jpg': "jpeg",
        'image/jpeg': "jpeg",
        'image/pjpeg': "jpeg",
        'image/gif': "gif",
    }

    def get_object(self) -> models.Post:
        return self._post

    def get_initial(self) -> dict[str, Any]:
        return dict(site=self.site)

    def get_success_url(self) -> str:
        return reverse('core:site', kwargs={'site': self.site.urn}) 
 
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if self.image_upload_field in request.FILES:
            return self.upload_image(request)
        return super().post(request, *args, **kwargs)

    def upload_image(self, request):
        image_file = request.FILES[self.image_upload_field]
        image_name = append_to_name(Path(image_file.name), date.today().isoformat())
        upload_dir = self.site.get_media_dir()

        if not upload_dir.exists():
            upload_dir.mkdir()

        if image_file.content_type not in self.image_types:
            data = json.dumps({
                'status': 405,
                'error': _('Bad image format.')
            }, cls=LazyEncoder)
            return HttpResponse(
                data, content_type='application/json', status=405)

        if image_file.size > settings.MAX_IMAGE_UPLOAD_SIZE:
            data = json.dumps({
                'status': 405,
                'error': _('Maximum image size exceeded') + str(settings.MAX_IMAGE_UPLOAD_SIZE / (1024 * 1024)) + "MB"
            }, cls=LazyEncoder)
            return HttpResponse(
                data, content_type='application/json', status=405)

        image = image_utils.scale_and_crop(image_file, settings.MAX_IMAGE_SIZE)
        image_buffer = BytesIO()
        image.save(image_buffer, format=self.image_format[image_file.content_type])
        media_path = default_storage.save(upload_dir / image_name, ContentFile(image_buffer.getvalue()))

        # image_mobile = image_utils.scale_and_crop(image_file, settings.MAX_IMAGE_SIZE_MOBILE, crop=True)
        # image_mobile.seek(0)
        # media_path = default_storage.save(upload_dir / append_to_name(image_name, "mobile"), ContentFile(image_mobile.tobytes()))

        return JsonResponse({'status': 200, 'link': settings.MEDIA_URL + media_path, 'name': str(image_name)})


class Images(SiteMixin, generic_views.View):
    def get(self, request, site):
        images_dir = self.site.get_media_dir()
        images_url = [{
            "link": f"{settings.MEDIA_URL}{self.site.urn}/{d.name}",
            "name": d.name
            } for d in images_dir.iterdir()]
        return JsonResponse(images_url, safe=False)


class Publish(SiteMixin, generic_views.View):
    def as_bool(value: str):
        return value.lower() in ("1", "true", "yes", "checked")
    
    def post(self, request: http.HttpRequest, **kwargs):
        publish = models.Publish(site=self.site, purge=bool(request.POST.get('purge', False)))
        if request.POST.get("post"):
            publish.post = models.Post(id=int(request.POST['post']))

velican2/core/templates/base.html
<!DOCTYPE html>
<html lang="cs-CZ">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/tailwind.css">
    <title>{% block head_title %}MicroB{% endblock %}</title>
    {%block "css"%}<style></style>{%endblock%}
    {% block extra_head %}{% endblock %}
</head>
<body>
    <nav>{% block "nav" %}
        <a href="{% url 'core:index' %}">Domů</a>
        <span>
        {% if user.is_authenticated %}
            {% if user_has_site %}
        <a href="{% url 'core:sites' %}">Moje domény</a>
            {% else %}
        <a href="{% url 'core:start' %}">Přidat doménu</a>
            {% endif %}
        <a href="{% url 'account_logout' %}">Odhlásit</a>
        {% else %}
        <a href="{% url 'account_login' %}">Přihlásit se</a>
        {% endif %}
        </span>
    {% endblock %}</nav>
    <main>
        {% if messages %}
        <div class="absolute top-10 z-10">
        <ul>
            {% for message in messages %}
            <li class="mb-3 list-none {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}bg-blue-300{% else %}{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}bg-green-300{%else%}bg-red-300{%endif%}{%endif%}" onclick="this.deleteNode()">{{message}}</li>
            {% endfor %}
        </ul>
        </div>
        {% endif %}

        {% block "main" %}
        <div class="content">{% block "content" %}{% endblock %}</div>
        {% endblock %}
    </main>
    {% block extra_body %}
    {% endblock %}
</body>
</html>

velican2/core/templates/category-add.html
{% extends 'base.html' %}

{% block "content" %}
    <form role="form" method="POST" class="__post">{% csrf_token %}
        <h1>Nová kategorie</h1>
        <label for="{{form.title.id_for_label}}">Název</label>{{form.name}}<br>
        <button type="submit" name="action" value="create">Vytvořit</button>
    </form>

    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{field.name}}: {{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    {% endif %}
{{ form.media }}
{% endblock %}

velican2/core/templates/post-add.html
{% extends 'base.html' %}

{% block "content" %}
    <form role="form" method="POST" class="__post">{% csrf_token %}
        {% if not post %}<h1>Článek pro {{site.urn}}</h1>{% else %}
        <h1>Překlad článku {{post.title}}({{post.lang}})</h1>
        <input type="hidden" name="{{form.translation_of.name}}" value="{{post.id}}">
        {% endif %}
        <label for="{{form.title.id_for_label}}">Nadpis</label>{{form.title}}<br>
        <label for="{{form.lang.id_for_label}}">Jazyk</label>{{form.lang}}<br>
        <label for="{{form.category.id_for_label}}">Kategorie</label>{{form.category}}{% if site.admin == user %}<a href="{% url 'core:category-add' site=site.urn %}" class="secondary ml-5">přidat kategorii</a>{%endif%}<br>
        <label for="{{form.description.id_for_label}}">Shrnutí</label><br>
        {{form.description}}
        <br>
        <button type="submit" name="action" value="create">Vytvořit</button>
    </form>

    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{field.name}}: {{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
    {% endif %}
{{ form.media }}
{% endblock %}

velican2/core/templates/post-delete.html
{% extends "base.html" %}

{% block "content" %}
<a href="{% url 'core:site' object.site.urn %}">zpět na doménu {{object.site.urn}}</a>

<form action="" method="post">
    {%csrf_token%}
    <label>Opravdu smazat {{object}}?</label>
    <button type="submit" name="action" value="delete">Ano, smazat</button>
</form>

{% endblock %}

velican2/core/templates/post.html
{% extends 'base.html' %}

{% block "css" %}
<style>
  textarea[name="description"], textarea[name="punchline"] {
    height: 4em;
  }
  .ui.secondary.pointing.menu.tab-martor-menu .martor-toolbar {
    padding: 0;
  }
  input[name="title"] {
    font-size: 14pt;
    margin-bottom: 1.5em;
  }
</style>
{% endblock %}

{% block extra_head %}
<script src="/static/core/image-explorer.js"></script>
<script>customElements.define("image-explorer", ImageExplorer);</script>
{% endblock %}

{% block "main" %}
<div class="container lg:w-2/3 mx-auto">
<a href="{% url 'core:site' site %}" class="underline">&lt; Zpět na seznam článků</a>
<form role="form" method="POST" class="__post">{% csrf_token %}
  {% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{field.name}}: {{ error|escape }}</strong>
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
    </div>
  {% endfor %}
  {% endif %}
  <section class="container">
    <h1>{%if post.translation_of %}Překlad článku "{{post.translation_of}} ({{post.translation_of.lang}})"{% else %}{{post}}{% endif %}</h1>
    <label for="{{form.title.id_for_label}}">Nadpis</label>{{form.title}}<br>
    <label for="{{form.lang.id_for_label}}">Jazyk</label>{{form.lang}} <a href="{% url 'core:post-add' site.urn %}?translation_of={{post.id}}">přidat překlad</a> <br>
    {% if post.created %}<label for="created">Uveřejněno</label>{{post.created}}<br>{% endif %}
    <label for="{{form.description.id_for_label}}">Shrnutí</label><br>
    {{form.description}}
  </section>
  <section>
    <image-explorer data-target="{{form.content.name}}" data-images-url="{% url 'core:images' site.urn %}"></image-explorer>
    <label for="{{form.content.id_for_label}}">Text</label><br>
    {{form.content}}
    {% if object.draft %}
    <button type="submit" name="action" value="save" class="mr-2">Uložit</button>
    {{form.draft}} <label for="{{form.draft.id_for_label}}">Stále je to jen koncept</label>
    {% else %}
    <button type="submit" name="action" value="save">Zveřejnit opravy</button>
    {% endif %}
    <a href="{% url 'core:post-delete' site.urn post.id %}" class="secondary float-right">Odstranit</a>
  </section>
  {% if object.draft %}
  <section>
    <label for="{{form.punchline.id_for_label}}">Oznámení o článku na sociální</label><br>
    {{form.punchline}}
    <br>
    <button type="submit" name="action" value="publish" class="mr-4">Publikovat</button>
    {{form.broadcast}}
    <label for="{{form.broadcast.id_for_label}}">Publikovat i na sociálních sítích?</label><br>
  </section>
  {% else %}
  {% if post.broadcast %}
  <section>
    <legend>Sociální sítě</legend>
    Fediverse: <a href="@moje.localhost/{{post.slug}}">@moje.localhost/{{post.slug}}</a><br>
    Facebook: publikováno<br>
    Instagram: čeká<br>
    TODO<br>
  </section>
  {% endif %}
  {% endif %}
</form>
</div>
{{ form.media }}

<script>
(function ($) {
  if (!$) {
    $ = django.jQuery;
  }
  var mainMartor = $('.main-martor')
  var field_name = mainMartor.data('field-name');
  var editorId = 'martor-' + field_name;
  var editor = ace.edit(editorId);

  /**
   * Select an image from gallery and insert given link into the editro
   */
  var galleryToImageLink = function (editor) {
    let img_expl = document.querySelector(`image-explorer[data-target=${field_name}]`);
    img_expl.show((imageData) => {
      var curpos = editor.getCursorPosition();
      editor.session.insert(curpos, '![' + imageData.name + '](' + imageData.link + ') ');
      editor.focus();
      editor.selection.moveTo(
        curpos.row,
        curpos.column + imageData.name.length + 2
      );
    });
  }

  editor.commands.addCommand({
    name: 'gallery',
    bindKey: {win: 'Ctrl-G',  mac: 'Command-G'},
    exec: galleryToImageLink,
    readOnly: false, // false if this command should not apply in readOnly mode
    // multiSelectAction: "forEach", optional way to control behavior with multiple cursors
    // scrollIntoView: "cursor", control how cursor is scolled into view after the command
  });

  $('.markdown-image-link[data-field-name=' + field_name + ']').click(function () {
    galleryToImageLink(editor);
  });
})(jQuery);
</script>
{% endblock %}

velican2/core/templates/site-edit.html
{% extends "base.html" %}

{% block "content" %}
<a href="{% url 'core:site' object.urn %}">zpět na doménu {{object.urn}}</a>
<form action="" method="post">
    {%csrf_token%}
    <ul>{{form.as_ul}}</ul>
    <button type="submit" name="action" value="save">Uložit</button>
</form>

{% endblock %}

velican2/core/templates/site.html
{% extends 'base.html' %}

{% block "css" %}
<style>
.markdownx {
    display: flex;
    flex-wrap: wrap;
}
a {
    text-decoration: underline;
}
h2 {
    margin-top: 2em;
}
h3 {
    margin-top: 0.2em;
}
</style>
{% endblock %}

{% block "content" %}
<h1>Doména {{site.urn}}</h1>
<a href="{% url 'core:site-edit' site.urn %}">Upravit</a><br>
Počet příspěvků: {{posts.length}}<br>
Počet odkazů: #TODO <br>

<h2 class="mt-2">Příspěvky</h2>
<a href="{% url 'core:post-add' object.urn %}" class="primary my-4">Přidat příspěvěk</a>
<h3>Rozepsané</h3>
<ul>
{% for draft in drafts %}
<li><a href="{% url 'core:post' site.urn draft.id %}">{{draft.title}} ({{draft.lang}})</a> překlady: {%for translation in draft.translations.all %} <a href="{% url 'core:post' site.urn translation.id %}">{{translation.lang}}</a>{% endfor %}</li>
{% endfor %}
</ul>

<h3>Poslední články</h3>
<ul>
{% for post in posts %}
<li><a href="{% url 'core:post' site.urn post.id %}">{{post.title}} ({{post.lang}})</a> překlady: {%for translation in post.translations.all %} <a href="{% url 'core:post' site.urn translation.id %}">{{translation.lang}}</a>{% endfor %}</li>
{% endfor %}
</ul>


<h2>Technologie</h2>
<h3>Vykreslování</h3>
<strong>{{object.engine}}</strong>: <a href="{{object.get_engine_url}}">nastavení</a><br>
<form action="{% url 'pelican:import-article' site.urn %}" method="POST" enctype="multipart/form-data">
    <h3>Importovat články</h3>
    {% csrf_token %}
    <section>
        <legend>Máte existující příspěvky napsané pro danou technologii? </legend>
        <input type="file" name="posts" multiple>
        <button type="submit" class="secondary">Importovat</button>
    </section>
</form>



<h3>Server</h3>
<strong>{{site.deployment}}</strong>: <a href="#">nastavení (TODO)</a><br>
{% if last_deploy %}
Poslední nasazení
{% if last_deploy.finished %}
    {% if last_deploy.success %}✅ {{last_deploy.finished}}
        {% if last_deploy.post %}<a href="{{last_deploy.post.get_url}}">{{last_deploy.post}}</a>{%endif%}
    {% else %}❌ {{last_deploy.message}}{% endif %}
{% else %}
    probíhá od {{last_deploy.started}} <a href="{% url 'core:site' site=site.urn %}">obnovit</a>
{% endif %}
<form action="{% url 'core:publish' object.urn %}" method="post">{% csrf_token %}
    {% if last_deploy.success == False %}
    <input type="hidden" name="post" value="{{post.id}}">
    <button name="action" type="submit" value="publish">Zkusit znovu</button>
    {% else %}
    <button name="action" type="submit" value="publish">Nasadit</button>
    <input type="checkbox" name="purge" id="purge" class="mx-2"><label for="purge">pročistit a přegenerovat vše</label>
    {%endif%}
</form>
{% endif %}


<h3>Export</h3>
{% if not git_exporter %}
<form action="{% url 'git:connect' site %}" method="post">{% csrf_token %}
<label for="git-repository">Propojit s GIT repozitářem:</label><input type="text" name="repository" id="git-repository"><br>
<label for="git-username">Uživatelské jméno:</label><input type="text" name="username" id="git-username"><br>
<label for="git-password">Heslo/Token:</label><input type="password" name="password" id="git-password"><br>
<input type="submit" name="action" value="Propojit" class="secondary">
</form>
{% else %}
Exportujeme vaše soubory do git repozitáře {{git_exporter.repository}}<br>
Poslední export: {{git_exporter.last_sync}}{%if git_exporter.error%}❌ {{git_exporter.error}}{%else%}✅{%endif%}<br>
{% endif %}

{% endblock %}