velican2/engines/pelican/urls.py
from django.urls import path
from . import views

app_name="pelican"
urlpatterns = [
    path("", views.SettingsList.as_view(), name="settings"),
    path("<str:site>/", views.SettingsDetail.as_view(), name="setting"),
    path("<str:site>/themes/", views.ThemeList.as_view(), name="themes"),
    path("<str:site>/import-article/", views.ImportArticle.as_view(), name="import-article"),
]

velican2/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve as serve_static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('pelican/', include('velican2.engines.pelican.urls')),
    path('git/', include('velican2.exporters.git.urls')),
    path('', include('velican2.core.urls', namespace="core")),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG :
    urlpatterns.insert(0,
        re_path(r'^media/(?P<path>.*)$', serve_static, {'document_root': settings.MEDIA_ROOT}),
    )

velican2/engines/pelican/models.py
import io
import pelican
import pelican.paginator
import re
import shutil
import subprocess
import toml
import urllib
import zipfile

from pathlib import Path
from datetime import datetime, date
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from django.core.files import File
from django.db import models
from django.contrib.auth import models as auth

from django.utils.translation import gettext as _
from velican2.core import models as core
from velican2.engines.pelican import logger
from pelican.tools import pelican_themes
#
# HACK: inject different err function so we can actually see errors
#
def pelican_themes_err(msg:str, die=None):
    raise RuntimeError(msg)
pelican_themes.err = pelican_themes_err

def theme_upload_to(instance, filename):
    return f"themes/{instance.name}/{Path(filename).name}"

def toml_validate(value):
    """Return None if the input is a valid TOML otherwise returns error message."""
    try:
        toml.loads(value)
        return None
    except toml.TomlDecodeError as e:
        return str(e)

class Theme(models.Model):
    """Git URL to the theme(s) that will be downloaded and if `not multiple` then installed automatically"""
    name = models.CharField(max_length=32, blank=True, primary_key=True, help_text="Must be set explicitely for cloning a repo under different name")
    url = models.CharField(max_length=256, null=False)
    description = models.TextField(blank=True, null=True)
    category = models.CharField(max_length=4, blank=False, null=False, default="blog", choices=(
        ("blog", _("Blog")), ("conf", _("Conference")), ("corp", _("Company"))
    ))
    image = models.ImageField(blank=True, null=True, upload_to=theme_upload_to, help_text="Screenshot images showcasing the theme")
    image1 = models.ImageField(blank=True, null=True, upload_to=theme_upload_to, help_text="Screenshot images showcasing the theme")
    image2 = models.ImageField(blank=True, null=True, upload_to=theme_upload_to, help_text="Screenshot images showcasing the theme")
    logo_size = models.CharField(max_length=7, null=True, blank=True, help_text="Ideal logo size in pixels; format: WxH (e.g. 350x200)")
    supports_custom_css = models.BooleanField(default=False)
    heading_size = models.CharField(max_length=9, null=True, blank=True, help_text="Ideal heading size in pixels; format: WxH (e.g. 1280x600)")
    theme_settings = models.TextField(blank=True, null=True, help_text="Define extra variables for the theme (using KEY = 'value' or KEY = conf.EXISTING_KEY)")
    user_settings = models.TextField(blank=True, null=True, help_text="Define extra variables for the theme (using toml syntax: KEY = 'value'")
    updated = models.DateTimeField(null=True, blank=True)
    log = models.TextField(null=True)

    __str__ = lambda self: self.name

    # Path where all themes are downlodaed (hence it is a class property).
    root_path = settings.APP_DIR / "pelican" / "theme"

    @property
    def path(self):
         return Theme.root_path / self.name

    @property
    def downloaded(self):
        if not self.name:
            return False
        return self.path.exists()

    @property
    def installed(self):
        if not self.name:
            return False
        return self.name in [Path(path).stem for path, _ in pelican_themes.themes()]

    @property
    def readme(self):
        for path in Path(self.path).iterdir():
            if "readme" in str(path).lower():
                return path.read_text(encoding="utf-8")
        return None

    def clean(self):
        errors = {}
        e = toml_validate(self.theme_settings)
        if e:
            errors["theme_settings"] = [ValidationError(e)]
        e = toml_validate(self.user_settings)
        if e:
            errors["user_settings"] = [ValidationError(e)]
        if errors:
            raise ValidationError(errors)

    def download(self, save=True):
        """Download theme from given URL to settings.PELICAN_THEMES path"""
        if not self.downloaded:
            Theme.root_path.mkdir(exist_ok=True)
        if self.url.endswith(".zip"):
            zip_path = self.path.with_suffix(".zip")
            urllib.request.urlretrieve(self.url, zip_path)
            z = zipfile.ZipFile(zip_path)
            l = z.infolist()
            if l[1].filename.strip("/").count("/") > 0:
                self.name = l[0].filename.strip("/")
                logger.debug("Only one folder found in the zipfile: " + self.name)
                z.extractall(Theme.path)
            else:
                logger.debug("Archive contains multiple files - extracting to: " + self.path)
                z.extractall(self.path)
            z.close()
            zip_path.unlink()
        else:
            if self.url.startswith("https") and not self.url.endswith(".git"):
                self.url += ".git"
            proc = None
            if self.downloaded:
                proc = subprocess.Popen( # update
                    ["git", "pull"], cwd=str(self.path),
                    stderr=subprocess.STDOUT, stdout=subprocess.PIPE, text=True)
            else:
                proc = subprocess.Popen( # download
                    ["git", "clone", "--recurse-submodules", self.url, self.name],
                    cwd=self.root_path, stderr=subprocess.STDOUT, stdout=subprocess.PIPE, text=True)
            if proc.wait() == 0:
                self.log = None
            else:
                self.log = proc.stdout.read()
                logger.error(self.log)
                if save:
                    self.save()
                return False
        if save:
            self.save()
        return True

    def reload(self, save=True):
        if not self.downloaded:
            return False

        image_paths = [path for path in Path(self.path).iterdir()
            if path.suffix in (".jpg", ".jpeg", ".png")]
        logger.debug(f"Found {len(image_paths)} images {image_paths}")
        self.image = File(image_paths[0].open("rb")) if len(image_paths) > 0 else None
        self.image1 = File(image_paths[1].open("rb")) if len(image_paths) > 1 else None
        self.image2 = File(image_paths[2].open("rb")) if len(image_paths) > 2 else None
        if not self.description:
            self.description = self.readme
        if save:
            self.save()

    def install(self, save=True):
        """Install the theme into pelican and django webserver"""
        if not self.downloaded:
            raise ValidationError("You must download the theme before installing it")
        if self.installed:
            return True
        try:
            pelican_themes.install(str(self.path), v=False)
        except Exception as e:
            self.log = str(e)
            logger.error(str(e))
        if save:
            self.save()

    def save(self, **kwargs):
        if not self.name:
            self.name = Path(self.url).stem
        if not self.downloaded:
            self.download(save=False)
        if self.downloaded and not self.installed:
            self.install(save=False)
        if not self.image and not self.description:
            self.reload(save=False)
        return super().save(**kwargs)

    def delete(self, **kwargs):
        pelican_themes.remove(self.name, v=False) # uninstall
        self.path.unlink() # remove
        return super().delete(**kwargs)

    def update(self, save=True):
        self.download(save=save)
        self.install(save=save)
        self.reload(save=save)
        self.updated = datetime.now()
        if save:
            return self.save()

    def update_conf(self, conf):
        """Update site's pelican configuration using mapping that will requires specific keys"""
        if self.theme_settings:
            mapping = toml.loads(self.theme_settings)
            for key, value in mapping.items():
                if isinstance(value, str) and value.startswith("conf."):
                    conf_key = value.split(".")[1]
                    if conf_key in conf:
                        conf[key] = conf[conf_key]
                        logger.debug(f'Re-using conf.{conf_key} as key')
                    else:
                        logger.warn(f'Key "{conf_key}" does not exist in `conf`')
                else:
                    conf[key] = value
        return conf


class Settings(models.Model):
    POST_URL_TEMPLATES = (
        ('{slug}.html', f"<{_('slug')}>.html"),
        ('{lang}/{slug}.html', f"<lang>/<{_('slug')}>.html"),
        ('{date:%Y}/{slug}.html', f"<{_('year')}>/<{_('slug')}>.html"),
        ('{date:%Y}/{date:%b}/{slug}.html', f"<{_('year')}>/<{_('month')}>/<{_('slug')}>.html"),
        ('{category}/{slug}.html', f"<{_('author')}>/<{_('slug')}>.html"),
        ('{category}/{slug}.html', f"<{_('category')}>/<{_('slug')}>.html"),
        ('{category}/{date:%Y}/{slug}.html', f"<{_('category')}>/<{_('year')}>/<{_('slug')}>.html"),
    )
    site = models.OneToOneField(core.Site, related_name="pelican", on_delete=models.CASCADE, db_index=True)
    theme = models.ForeignKey(Theme, null=True, on_delete=models.DO_NOTHING)
    show_pages_in_menu = models.BooleanField(default=True, null=False, help_text=_("Display pages in menu"))
    show_categories_in_menu = models.BooleanField(default=True, null=False, help_text=_("Display categories in menu"))
    post_url_template = models.CharField(max_length=255, choices=POST_URL_TEMPLATES, default=POST_URL_TEMPLATES[0][0], help_text=_("URL of your post - can contain post's category, creation date or just slug"))
    page_url_prefix = models.CharField(max_length=35, blank=True, default="", help_text=_("Pages URL prefix (pages urls will look like 'prefix/{slug}.html')"))
    category_url_prefix = models.CharField(max_length=35, default=_("category"), help_text=_("Category URL prefix (pages urls will look like 'prefix/{slug}.html')"))

velican2/engines/pelican/forms.py
from django import forms

from . import models

class SettingsForm(forms.ModelForm):
    class Meta:
        model = models.Settings
        exclude = ()

velican2/engines/pelican/views.py
from typing import Any
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models.query import QuerySet
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import gettext as _
from django.views import generic
from django import forms

from . import logger
from .models import Settings, Theme, ThemeSettings
from .forms import SettingsForm
from velican2.core.views import SiteMixin


class SettingsList(LoginRequiredMixin, generic.ListView):
    model = Settings

    def get_queryset(self) -> QuerySet[Any]:
        return Settings.objects.filter(site__admin=self.request.user)


class SettingsDetail(SiteMixin, generic.UpdateView):
    model = Settings
    form_class = SettingsForm
    template_name = "pelican/settings_detail.html"

    def get_object(self, queryset: QuerySet[Any] = None) -> Settings:
        return Settings.objects.get(site=self.site)
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return super().get_context_data(**kwargs,
                                        themes=Theme.objects.filter(image__isnull=False).exclude(image=""))


class ImportArticle(SiteMixin, generic.View):
    model = Settings

    def get_object(self, queryset: QuerySet[Any] = None) -> Settings:
        return Settings.objects.get(site=self.site)

    def get(self, request, site:str):
        return redirect("core:site", site=site)

    def post(self, request, site:str):
        pelican = self.get_object()
        for file in request.FILES.getlist('posts'):
            pelican.import_article(file, request.user)
            messages.info(request, " ".join((_("File"), file.name, _("imported sucessfully"))))
        # except Exception as e:
        #     logger.error(type(e))
        #     logger.error(e)
        #     messages.error(request, _("Could not process file"))
        return redirect(request.headers['Referer'])


class ThemeList(LoginRequiredMixin, generic.ListView):
    template_name = "pelican/theme_list.html"
    model = Theme

    class Form(forms.Form):
        theme_id = forms.CharField(required=True)
        settings = forms.CharField(required=False, widget=forms.Textarea)

        def clean_theme_id(self, value):
            try:
                return Theme.objects.get(pk=value)
            except Exception as e:
                raise forms.ValidationError(str(e))

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        logger.debug(f"Context: {kwargs}")
        pelican = Settings.objects.get(id=self.kwargs['id'])
        kwargs.update(
            pelican=pelican,
            settings={theme_id: settings for (theme_id, settings) in ThemeSettings.objects.filter(
                pelican=pelican).values_list('theme_id', 'settings')}
        )
        return kwargs

    def post(self, request, *args, **kwargs):
        form = self.Form(request.POST)
        if form.is_valid():
            request.user.site
            return HttpResponseRedirect()
        self.object_list=self.get_queryset()
        return self.render_to_response(
            self.get_context_data(form=form))

velican2/engines/pelican/templates/pelican/base.html
{% extends "base.html" %}

velican2/engines/pelican/templates/pelican/settings_detail.html
{% extends "pelican/base.html" %}

{%block "css"%}<style>
    input {
        margin-bottom: 1em;
    }
    input[type='text'], select {
        margin-bottom: 1.5em;
    }
    legend {
        font-size: 16pt;
        font-weight: 500;
        margin-bottom: 0.8em;
    }
</style>{%endblock%}

{% block "content" %}
<h1>Nastavení vzhledu {{object.site}}</h1>
<form method="POST">
    {% csrf_token %}
    <section>
        <legend>Nastavení URL</legend>
        <label for="{{form.post_url_template.id_for_label}}">{{form.post_url_template.help_text}}</label><br>{{form.post_url_template}}<br>
        <label for="{{form.page_url_prefix.id_for_label}}">{{form.page_url_prefix.help_text}}</label><br>{{form.page_url_prefix}}<br>
        <label for="{{form.category_url_prefix.id_for_label}}">{{form.category_url_prefix.help_text}}</label><br>{{form.category_url_prefix}}<br>
        <label for="{{form.author_url_prefix.id_for_label}}">{{form.author_url_prefix.help_text}}</label><br>{{form.author_url_prefix}}<br>
        <label for="{{form.tags_url_prefix.id_for_label}}">{{form.tags_url_prefix.help_text}}</label><br>{{form.tags_url_prefix}}<br>
    </section>
    <section>
        <legend>Zobrazení stránky</legend>
        {{form.show_pages_in_menu}} <label for="{{form.show_pages_in_menu.id_for_label}}">{{form.show_pages_in_menu.help_text}}</label><br>
        {{form.show_categories_in_menu}} <label for="{{form.show_categories_in_menu.id_for_label}}">{{form.show_categories_in_menu.help_text}}</label><br>
        {{form.show_internal_pages_author}} <label for="{{form.show_internal_pages_author.id_for_label}}">{{form.show_internal_pages_author.help_text}}</label><br>
        {{form.show_internal_pages_categories}} <label for="{{form.show_internal_pages_categories.id_for_label}}">{{form.show_internal_pages_categories.help_text}}</label><br>
        {{form.show_internal_pages_tags}} <label for="{{form.show_internal_pages_tags.id_for_label}}">{{form.show_internal_pages_tags.help_text}}</label><br>
    </section>

    <section class="grid lg:grid-cols-3 gap-2">
        <legend>Vzhled</legend>
        {% for theme in themes %}
        <div>
            <input type="radio" name="theme" value="{{theme.name}}" id="{{theme.name}}"{%if object.theme == theme%} checked{%endif%}>
            <label for="{{theme.name}}">{{theme.name}}</label>
            <img src="{{theme.image.url}}" class="w-fit">
        </div>
        {% endfor %}
    </section>

    <button type="submit">Uložit</button>
</form>

{% endblock %}

velican2/engines/pelican/templates/pelican/settings_list.html
{% extends "pelican/base.html" %}


{% block content %}
{% for object in object_list %}
<ul>
    <li><a href="{% url 'pelican:settings' id=object.id %}">{{object.site.domain}}/{{object.site.path}}</a></li>
</ul>
{% endfor %}
{% endblock %}

velican2/engines/pelican/templates/pelican/theme_list.html
{% extends "pelican/base.html" %}
{% load static %}

{% block style %}
    {{ super }}
    form.selected {
        background-color: #eeffee;
    }
{% endblock %}

{% block content %}

{% for theme in object_list %}
<form method="POST" {% if theme == pelican.theme %}class="selected"{% endif %}>
    <h3>{{theme.name}}</h3>
    {% csrf_token %}
    <input type="hidden" name="theme_id" value="{{theme.id}}"/>
    <textarea name="settings" cols="30" rows="10">{% if theme.id in settings %}{{settings}}{% else %}{{theme.mapping}}{% endif %}</textarea>
    <input type="submit" value="Select">
    <div class="gallery">
{% if theme.image %}<img src="{% get_media_prefix %}{{theme.image.name}}">{% endif %}
{% if theme.image1 %}<img src="{% get_media_prefix %}{{theme.image1.name}}">{% endif %}
{% if theme.image2 %}<img src="{% get_media_prefix %}{{theme.image2.name}}">{% endif %}
    </div>
</form>
<br>
{% endfor %}

{% endblock %}